apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mini-reco

resources:
  - namespace.yaml
  - configmap.yaml
  - trace-collector.yaml
  - recalls.yaml
  - gateway.yaml
  - autoscaling.yaml
  - disruption-budget.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mini-reco
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true
