apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: mini-reco-access-layer
    newName: mini-reco-access-layer
    newTag: v17

patches:
  - path: gateway-nodeport.yaml
